name: laundryday
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  http: ^1.2.1
  intl: any
  go_router: ^12.1.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_riverpod: ^2.4.9
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.0.9
  geocoding: ^3.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.2
  path: ^1.8.2
  dotted_border: ^2.1.0
  voice_message_package: ^2.2.1
  record: ^5.1.0
  image_cropper: ^5.0.1
  flutter_rating_bar: ^4.0.1
  multi_select_flutter: ^4.1.3
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  shimmer: ^3.0.0
  fpdart: ^1.1.0
  pusher_channels_flutter: ^2.2.1
  crypto: ^3.0.0
  audioplayers: ^6.0.0
  flutter_local_notifications: ^17.2.2
  location: ^6.0.2
  photo_view: ^0.14.0
  device_info_plus: ^10.1.2
  cached_network_image: any
  firebase_messaging: ^15.1.1
  flutter_notification_channel: ^2.0.0
  bot_toast: ^4.1.3
  cloud_firestore: ^5.4.1
  uuid: ^4.5.0
  googleapis_auth: ^1.6.0
  firebase_storage: ^12.3.1
  flutter_image_compress: ^2.3.0
  just_audio: ^0.9.40
  flutter_phone_direct_caller: ^2.1.1
  easy_localization: ^3.0.7
  restart_app: any
  app_settings: ^5.1.1
  permission_handler: ^11.3.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.jpg"
  min_sdk_android: 21 #

  flutter_lints: ^2.0.0


flutter:
  generate: true #
  
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/vectors/
    - assets/category_banner/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
