name: laundryday
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  http: ^1.2.1
  intl: ^0.18.1
  go_router: ^13.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_riverpod: ^2.4.9
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  url_launcher: ^6.0.9
  geocoding: ^2.0.0
  geolocator: ^10.1.0
  app_settings: ^5.1.1
  cached_network_image: ^3.3.1
  sqflite: ^2.3.1
  path_provider: ^2.1.2
  flutter_swipe_action_cell: ^3.1.3
  uuid: ^4.3.3
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  permission_handler: ^10.0.0
  path: ^1.8.2
  dotted_border: ^2.1.0
  voice_message_package: ^2.1.4
  record: ^5.0.4
  image_cropper: ^5.0.1
  faker: ^2.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.1
  moyasar: ^2.0.7
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.18.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  generate: true
  
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/vectors/
    - assets/carpets/
    - assets/category_banner/
    - assets/clothes/laundry/
    - assets/blankets_and_linen/

