name: laundryday
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  http: ^1.2.1
  intl: ^0.19.0
  go_router: ^13.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_riverpod: ^2.4.9
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.0.9
  geocoding: ^3.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.2
  path: ^1.8.2
  dotted_border: ^2.1.0
  voice_message_package: ^2.2.1
  record: ^5.1.0
  image_cropper: ^5.0.1
  flutter_rating_bar: ^4.0.1
  multi_select_flutter: ^4.1.3
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  shimmer: ^3.0.0
  fpdart: ^1.1.0
  moyasar: ^2.0.12
  pusher_channels_flutter: ^2.2.1
  crypto: ^3.0.0
  audioplayers: ^6.0.0
  flutter_local_notifications: ^12.0.0
  countdown_progress_indicator: ^0.1.3
  location: ^7.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.jpg"
  min_sdk_android: 21 #

  flutter_lints: ^2.0.0


flutter:
  generate: true
  
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/audios/
    - assets/vectors/
    - assets/category_banner/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
