class RouteNames {
  RouteNames._();
  static final String login = "login";
  static final String home = "home";
  static final String verification = "verification";
  static final String signUp = "signup";
  static final String splash = "splash";
  static final String profile = "profile";
  static final String carpetsScreen = "carpets";
  static final String furnitureScreen = "furniture";
  static final String serviceDetail = "service_detail";
  static final String more = "more";
  static final String services = "services";
  static final String addNewAddress = "add_new_address";
  static final String updateAddress = "update_address";
  static final String myAddresses = "my_addresses";
  static final String settings = "settings";
  static final String editProfile = "edit_profile";
  static final String agentRegistration = "agent_registration";
  static final String orders = "orders";
  static final String orderDetails = "order_details";
  static final String fetchAgentAddress = "fetch_agent_address";
  static final String carpetOrderCheckout = "carpet_order_checkout";
  static final String orderReview = "order_review";
  static final String help = "help";
  static final String businessPartner = "business_partner";
  static final String clothesServiceDetail = "clothes_service_detail";
  static final String clothesCategory = "clothes_category";
  static final String laundries = "laundries";
  static final String laundryItems = "blankets_category";
  static final String deliveryPickup = "delivery_pickup";
  static final String orderSummary = "order_summary";
  static final String orderChat = "order_chat";
  static final String findCourier = "find_courier";
  static final String orderProcess = "order_process";
  static final String orderCheckout = "order_checkout";
  static final String invoice = "invoice";
  static final String taxInvoice = "tax_invoice";
  static final String rateCourier = "rate_courier";
  static final String viewImage = "view_image";
  static final String viewNetworkImage = "view_network_image";

  static final String addNewCard = "add_new_card";
  static final String laundryCareGuide = "laundry_care_guide";
  static final String paymentOptions = "payment_options";
  static final String addLaundry = "add_laundry";
}
