// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8JWUDRTDvYIn7lIK8R1fC6T5Piw71_Qk',
    appId: '1:709376690173:web:f38aeb03877c374273fb94',
    messagingSenderId: '709376690173',
    projectId: 'laundryday-ef178',
    authDomain: 'laundryday-ef178.firebaseapp.com',
    storageBucket: 'laundryday-ef178.appspot.com',
    measurementId: 'G-CWH0XF2REL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoCg0upiKZBuUv6NysavvBZGydqls5_Fo',
    appId: '1:709376690173:android:a49c9d3f6515989173fb94',
    messagingSenderId: '709376690173',
    projectId: 'laundryday-ef178',
    storageBucket: 'laundryday-ef178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT07uS0VwfIsf4GxRdK9bxftiRz1a48Ng',
    appId: '1:709376690173:ios:466ee606939ee33573fb94',
    messagingSenderId: '709376690173',
    projectId: 'laundryday-ef178',
    storageBucket: 'laundryday-ef178.appspot.com',
    iosBundleId: 'com.example.laundryday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT07uS0VwfIsf4GxRdK9bxftiRz1a48Ng',
    appId: '1:709376690173:ios:466ee606939ee33573fb94',
    messagingSenderId: '709376690173',
    projectId: 'laundryday-ef178',
    storageBucket: 'laundryday-ef178.appspot.com',
    iosBundleId: 'com.example.laundryday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8JWUDRTDvYIn7lIK8R1fC6T5Piw71_Qk',
    appId: '1:709376690173:web:2a35d37fb9bc16e373fb94',
    messagingSenderId: '709376690173',
    projectId: 'laundryday-ef178',
    authDomain: 'laundryday-ef178.firebaseapp.com',
    storageBucket: 'laundryday-ef178.appspot.com',
    measurementId: 'G-Z9PQN67H6K',
  );
}
